# Introduction {#intro}


## Opportunities in GIS

Significant opportunities exist in the development of GIS. 

## Simple poly talk here



Individual Objects are - potentially-composite - *simple and valid* shapes with a topological dimension of 0 (zero - points), 1 (one - lines) or 2 ("polygons"). Technically these are called POINT, MULTIPOINT, LINESTRING,  MULTILINESTRING, POLYGON and MULTIPOLYGON as per the Open Geospatial Consortium’s (OGC) OpenGIS Specifications. The "MULTI" refers to the case where a single object is made up of more than one simple and valid POINT, LINESTRING, or POLYGON. 


This is what PostGIS has to say: 

> A POINT is inheritably simple as a 0-dimensional geometry object.
> 
> MULTIPOINTs are simple if no two coordinates (POINTs) are equal (have identical coordinate values).
> 
> A LINESTRING is simple if it does not pass through the same POINT twice (except for the endpoints, in which case it is referred to as a linear ring and additionally considered closed).
> 
> A MULTILINESTRING is simple only if all of its elements are simple and the only intersection between any two elements occurs at POINTs that are on the boundaries of both elements.
> 
> By definition, a POLYGON is always simple. It is valid if no two rings in the boundary (made up of an exterior ring and interior rings) cross. The boundary of a POLYGON may intersect at a POINT but only as a tangent (i.e. not on a line). A POLYGON may not have cut lines or spikes and the interior rings must be contained entirely within the exterior ring.
> 
> A MULTIPOLYGON is valid if and only if all of its elements are valid and the interiors of no two elements intersect. The boundaries of any two elements may touch, but only at a finite number of POINTs.


http://postgis.net/docs/manual-1.4/ch04.html#OGC_Validity

**NOTE:** I don't understand why PostGIS refers to "geometric dimension" here. The geometric dimension is usually 2, for X and Y (or longitude and latitude). How would we describe a LINESTRING that has X, Y, Z coordinate values? A 1D geometry with 3 ?? dimensions. To me this is a 1D topological shape with 3D geometry. 



## Terminology summary 

Entity | PostGIS | ggplot2::fortify | raster::geom | sp
-------|---------|------------------|--------------|------
Object | feature | id | object | *-named by class-*  
Branch | element | piece | part |  *-named by class-*  
Vertex | point   | long/lat | x/y | *coordinate*

Note that `sp` is a bit inconsistent since it doesn't have Point and Points objects as analoges to Line/Polygon and Lines/Polygons. Also, sp implemented a shapefile-like logic where a flat list of linestrings composes a multi-polygon and each is badged as hole or island, corresponding to its cooridinate order, but there's an ambiguity as to which hold belongs to which island. Simple features removes this ambiguity, since any Polygon has only one island, the first ring - and any subsequent ring is a hole in that island. sfr for R is an update from sp to reflect this newer standard. Also, ring order convention in sp is opposite to the SF standard . . .

Illustration of the sp list-bag of holes/islands, verus the systematic sf version. (Also note that the rings must be internal to the island, but that's a different kind of validation. 

But, the entire topic is rife with these confusing problems so let's move on. 




